# Generated by Django 5.1.6 on 2025-06-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chattable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagetable',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
