# Generated by Django 5.1.6 on 2025-07-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessagetable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagetable',
            name='readed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessagetable',
            name='readed_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
