# Generated by Django 5.1.6 on 2025-07-22 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_service', '0001_initial'),
        ('user', '0004_remove_employeeaccounttabledata_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.storeservicetabledata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccounttabledata')),
            ],
            options={
                'db_table': 'comment_table',
            },
        ),
    ]
