# Generated by Django 5.1.6 on 2025-04-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTableData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('service_subtype', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('volume', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('stock_modified_date', models.DateField()),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producttabledata')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
    ]
