# Generated by Django 5.1.6 on 2025-07-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_productitemtable_discount_and_more'),
        ('publicidad', '0002_alter_publicidadtable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpublicidad',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productpublicidad',
            name='type',
            field=models.CharField(default='descuento', max_length=10),
        ),
        migrations.AddField(
            model_name='servicepublicidad',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepublicidad',
            name='type',
            field=models.CharField(default='descuento', max_length=10),
        ),
        migrations.AlterField(
            model_name='productpublicidad',
            name='publicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.publicidadtable'),
        ),
        migrations.AlterField(
            model_name='publicidadimage',
            name='publicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.publicidadtable'),
        ),
        migrations.AlterField(
            model_name='servicepublicidad',
            name='publicidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.publicidadtable'),
        ),
        migrations.CreateModel(
            name='SelectedPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.productitemtable')),
                ('publicidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.publicidadtable')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.serviceitemtable')),
            ],
            options={
                'db_table': 'selected_publicidad',
            },
        ),
    ]
