# Generated by Django 5.1.6 on 2025-07-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0003_productpublicidad_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidadtable',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
