# Generated by Django 5.1.6 on 2025-08-08 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_productitemtable_discount_and_more'),
        ('publicidad', '0004_publicidadtable_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedpublicidad',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.productitemtable'),
        ),
        migrations.AlterField(
            model_name='selectedpublicidad',
            name='service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.serviceitemtable'),
        ),
    ]
