# Generated by Django 5.1.6 on 2025-06-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_service', '0001_initial'),
        ('user', '0004_remove_employeeaccounttabledata_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField()),
                ('card_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('progress_status', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
        migrations.CreateModel(
            name='ServiceItemTable',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('payment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_info_day', models.DateField()),
                ('date_info_start_time', models.TimeField()),
                ('date_info_end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordertable')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.storeservicetabledata')),
            ],
            options={
                'db_table': 'service_item_table',
            },
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.employeeaccounttabledata')),
                ('service_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.serviceitemtable')),
            ],
            options={
                'db_table': 'payment_table',
                'constraints': [models.UniqueConstraint(fields=('employee', 'service_item'), name='unique_employee_service_item')],
            },
        ),
    ]
