# Generated by Django 5.1.6 on 2025-06-17 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_serviceitemtable_base_price'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemTable',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordertable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producttabledata')),
            ],
            options={
                'db_table': 'product_item_table',
                'constraints': [models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product')],
            },
        ),
    ]
