# Generated by Django 5.1.6 on 2025-06-18 08:01

import django.db.models.deletion
from django.db import migrations, models
from typing import Any

def set_client(apps: Any, schema_editor: Any) -> None:
    Order = apps.get_model('order', 'OrderTable')
    User = apps.get_model('user', 'UserAccountTableData')

    for order in Order.objects.all():
        order.client = User.objects.all().first()
        order.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_productitemtable'),
        ('user', '0004_remove_employeeaccounttabledata_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='client_id',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.useraccounttabledata'),
            preserve_default=False,
        ),
        migrations.RunPython(set_client),
        migrations.AlterField(
            model_name='ordertable',
            name='client',
            field=models.ForeignKey(null=False, on_delete=models.CASCADE, to='user.useraccounttabledata'),
        )
    ]
