# Generated by Django 5.1.6 on 2025-06-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_ordertable_client_id_ordertable_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='client_confirmed',
            field=models.CharField(default='not_confirmado', max_length=50),
            preserve_default=False,
        ),
    ]
