# Generated by Django 5.1.6 on 2025-07-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordertable_client_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemtable',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitemtable',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
