# Generated by Django 5.1.6 on 2025-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_productitemtable_discount_serviceitemtable_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
