# Generated by Django 5.1.6 on 2025-07-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordertable_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
