# Generated by Django 5.1.6 on 2025-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_ordertable_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=5),
        ),
    ]
