# Generated by Django 5.1.6 on 2025-07-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_ordertable_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemtable',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='serviceitemtable',
            name='discount',
        ),
    ]
