# Generated by Django 5.1.6 on 2025-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_productitemtable_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
