# Generated by Django 5.1.6 on 2025-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordertable_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
