# Generated by Django 5.1.6 on 2025-08-17 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_ordertable_created_date'),
        ('user', '0004_remove_employeeaccounttabledata_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttable',
            name='service_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.serviceitemtable'),
        ),
        migrations.CreateModel(
            name='EmployeePaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeeaccounttabledata')),
            ],
            options={
                'db_table': 'employee_payment_table',
            },
        ),
    ]
