# Generated by Django 5.1.6 on 2025-08-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_paymenttable_service_item_employeepaymenttable'),
        ('user', '0004_remove_employeeaccounttabledata_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttable',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employeeaccounttabledata'),
        ),
    ]
