# Generated by Django 5.1.6 on 2025-03-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
            ],
            options={
                'db_table': 'question_choice',
            },
        ),
        migrations.CreateModel(
            name='QuestionTableData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('input_type', models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('CHOICE', 'CHOICE')], max_length=50)),
                ('created_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'store_service_question',
            },
        ),
        migrations.CreateModel(
            name='StoreServiceTableData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ENABLE', 'ENABLE'), ('DISABLE', 'DISABLE')], max_length=50)),
                ('type', models.CharField(choices=[('CABELLO', 'CABELLO'), ('SPA', 'SPA'), ('UÑAS', 'UÑAS'), ('MAQUILLAJE', 'MAQUILLAJE')], max_length=50)),
                ('duration', models.TimeField()),
                ('created_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'store_service',
            },
        ),
        migrations.CreateModel(
            name='ChoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.questionchoice')),
            ],
            options={
                'db_table': 'question_image',
            },
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.questiontabledata'),
        ),
        migrations.CreateModel(
            name='StoreServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.storeservicetabledata')),
            ],
            options={
                'db_table': 'store_service_price',
            },
        ),
        migrations.CreateModel(
            name='StoreServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.storeservicetabledata')),
            ],
            options={
                'db_table': 'store_service_image',
            },
        ),
        migrations.AddField(
            model_name='questiontabledata',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.storeservicetabledata'),
        ),
    ]
