# Generated by Django 5.1.6 on 2025-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontabledata',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
