# Generated by Django 5.1.6 on 2025-04-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccounttabledata')),
            ],
            options={
                'db_table': 'user_card',
            },
        ),
        migrations.CreateModel(
            name='DebitPayment',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ok', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField()),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.usercard')),
            ],
            options={
                'db_table': 'debit_payment',
            },
        ),
    ]
