# Generated by Django 5.1.6 on 2025-08-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('user', '0004_remove_employeeaccounttabledata_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='card_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(fields=('id', 'user'), name='unique_user_card'),
        ),
    ]
