# Generated by Django 5.1.6 on 2025-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_usercard_card_id_alter_usercard_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='number',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercard',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
