# Generated by Django 5.1.6 on 2025-03-18 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountTableData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('ENABLE', 'ENABLE'), ('DISABLE', 'DISABLE')], max_length=25)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=25)),
                ('birthdate', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='RoleTableData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccountTableData',
            fields=[
                ('useraccounttabledata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.useraccounttabledata')),
                ('dni', models.CharField(max_length=250, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'employee_account',
            },
            bases=('user.useraccounttabledata',),
        ),
        migrations.CreateModel(
            name='RolPermissionTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=250)),
                ('permission', models.CharField(max_length=250)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.roletabledata')),
            ],
            options={
                'db_table': 'role_permission',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission', 'access'), name='unique_role_permission')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRoleTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.roletabledata')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employeeaccounttabledata')),
            ],
            options={
                'db_table': 'employee_role',
                'constraints': [models.UniqueConstraint(fields=('employee', 'role'), name='unique_employee_role')],
            },
        ),
    ]
