# Generated by Django 5.1.6 on 2025-03-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPermissionTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=250)),
                ('permission', models.CharField(max_length=250)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.roletabledata')),
            ],
            options={
                'db_table': 'role_permission',
                'constraints': [models.UniqueConstraint(fields=('role', 'permission', 'access'), name='unique_role_permission')],
            },
        ),
    ]
