# Generated by Django 5.1.6 on 2025-05-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccounttabledata',
            name='payment_type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
