# Generated by Django 5.1.6 on 2025-03-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employeecategoriestabledata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeecategoriestabledata',
            constraint=models.UniqueConstraint(fields=('employee', 'category'), name='unique_employee_category'),
        ),
        migrations.AlterModelTable(
            name='employeecategoriestabledata',
            table='employee_categories',
        ),
    ]
