# Generated by Django 5.1.6 on 2025-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employeeaccounttabledata_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccounttabledata',
            name='payment_type',
            field=models.CharField(max_length=25),
        ),
    ]
