# Generated by Django 5.1.6 on 2025-06-10 02:14

from django.db import migrations, models
import uuid

def add_dni_to_useraccounts(apps, schema_editor):
    UserAccount = apps.get_model('user', 'UserAccountTableData')
    for user in UserAccount.objects.all():
        
        user.dni = user.phone_number
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employeeaccounttabledata_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaccounttabledata',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='employeeaccounttabledata',
            name='photo',
        ),
        migrations.AddField(
            model_name='useraccounttabledata',
            name='dni',
            field=models.CharField(max_length=250, unique=True, null=True),  # TEMPORALMENTE null
        ),
        migrations.AddField(
            model_name='useraccounttabledata',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounttabledata',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=25),
        ),
        migrations.RunPython(add_dni_to_useraccounts),
        migrations.AlterField(
            model_name='useraccounttabledata',
            name='dni',
            field=models.CharField(max_length=250, unique=True),  # ahora null=False
        ),
    ]