# Generated by Django 5.1.6 on 2025-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTableData',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
