# Generated by Django 5.1.6 on 2025-07-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
