# Generated by Django 5.1.6 on 2025-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_usernotificationtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('to', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
