# Generated by Django 5.1.6 on 2025-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtable',
            name='type',
            field=models.CharField(default='INSTANTANEA', max_length=50),
            preserve_default=False,
        ),
    ]
