# Generated by Django 5.1.6 on 2025-07-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notificationtable_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='redirect_to',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
