# Generated by Django 5.1.6 on 2025-07-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notificationlogtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='notification_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
