# Generated by Django 5.1.6 on 2025-06-13 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('store_service', '0001_initial'),
        ('user', '0004_remove_employeeaccounttabledata_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useraccounttabledata')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_service.questiontabledata')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.serviceitemtable')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='ImageAnswerTableData',
            fields=[
                ('answertabledata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answertabledata')),
                ('images', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'image_answer',
            },
            bases=('answers.answertabledata',),
        ),
        migrations.CreateModel(
            name='TextAnswerTableData',
            fields=[
                ('answertabledata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answers.answertabledata')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'text_answer',
            },
            bases=('answers.answertabledata',),
        ),
        migrations.AddConstraint(
            model_name='answertabledata',
            constraint=models.UniqueConstraint(fields=('client', 'question', 'service_item'), name='unique_item_question_answer'),
        ),
    ]
