# Generated by Django 5.1.6 on 2025-06-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageanswertabledata',
            old_name='images',
            new_name='image',
        ),
    ]
